language: clojure
lein: 2.7.1
before_script:
  - mkdir -p target
  - git clone http://github.com/plandes/clj-zenbuild
<<<<<<< HEAD
script: ZBHOME=clj-zenbuild make checkdep
=======
script: ZBHOME=clj-zenbuild make checkdep test
>>>>>>> merge
jdk:
  - oraclejdk8
